OPS-6102 Update version.json
aerospike/trino-aerospike.docker pull request #2
Opened 2022-09-12 21:46 UTC by mcoberly2

2022-09-12 21:49 UTC, mcoberly2 commented
@reugn 
Please add @mcoberly2  @pvinh-spike @ishaanb to the People for this trino-aerospike.docker repositoy.
We do not have any rights to even request reviewers or be requested as reviewers.

Additionally, @reugn please review & @ishaanb please review when you gain rights.

2022-09-13 06:13 UTC, reugn requested changes

2022-09-13 06:13 UTC, reugn commented on version.json
> +    "393": "4.1.0-391"
Add
```json
    "394": "4.1.0-391",
    "395": "4.1.0-391"
```

2022-09-13 17:33 UTC, mcoberly2 commented on version.json
> +    "393": "4.1.0-391"
updated

2022-09-13 18:31 UTC, pvinh-spike approved these changes
LGTM

2022-09-13 18:41 UTC, merged